# Job Market Scraper Configuration
scraping:
  job_titles:
    SA:
      - "data engineer"
      - "data analyst" 
      - "data scientist"
      - "machine learning engineer"
      - "generative ai engineer"
      - "ai research scientist"
      - "ai engineer"
      - "ai consultant"
      - "ai product manager"
      - "ai specialist"
      - "ai solutions architect"
      - "nlp engineer"
      - "computer vision engineer"
      - "deep learning engineer"
      - "ml ops engineer"
      - "prompt engineer"
      - "data governance analyst"
      - "data governance specialist"
      - "data governance manager"
      - "data compliance analyst"
      - "data privacy officer"
      - "data quality analyst"
      - "data steward"
      - "data management specialist"
      - "master data management (mdm) specialist"
      - "information governance manager"
      - "business intelligence"
      - "cloud engineer"
      - "cloud infrastructure engineer"
      - "cloud solutions architect"
      - "cloud systems administrator"
      - "cloud network engineer"
      - "azure engineer"
      - "aws engineer"
      - "google cloud engineer"
      - "cybersecurity analyst"
      - "cybersecurity engineer"
      - "information security analyst"
      - "security operations center analyst"
      - "cloud security engineer"
      - "devops engineer"
      - "cloud devops engineer"
      - "site reliability engineer"
      - "platform engineer"
      - "game developer"
      - "unity developer"
      - "unreal engine developer"
      - "game designer"
      - "game programmer"
      - "software engineer"
      - "frontend developer"
      - "backend developer"
      - "full stack developer"
      - "web developer"
      - "mobile app developer"
      - "android developer"
      - "ios developer"
      - "application developer"
    CA:
      - "data engineer"
      - "data analyst" 
      - "data scientist"
      - "machine learning engineer"
      - "business intelligence"
    US:
      - "data engineer"
      - "data analyst" 
      - "data scientist"
      - "machine learning engineer"
      - "business intelligence"
    AE:
      - "data engineer"
      - "data analyst" 
      - "data scientist"
      - "machine learning engineer"
      - "business intelligence"
    EG:
      - "data engineer"
      - "data analyst" 
      - "data scientist"
      - "machine learning engineer"
      - "business intelligence"
  
  locations:
    - country: "SA"
      domain: "sa.indeed.com"
      location_name: "Saudi Arabia"
      log_prefix: "SA"
    - country: "CA"
      domain: "ca.indeed.com"
      location_name: "Canada"
      log_prefix: "CA"
    - country: "US"
      domain: "indeed.com"
      location_name: 
        - "New York, NY"
        - "Los Angeles, CA"
        - "Chicago, IL"
        - "Houston, TX"
        - "Phoenix, AZ"
        - "Philadelphia, PA"
        - "San Antonio, TX"
        - "San Diego, CA"
        - "Dallas, TX"
        - "Jacksonville, FL"
        - "Fort Worth, TX"
        - "San Jose, CA"
        - "Austin, TX"
        - "Charlotte, NC"
        - "Columbus, OH"
        - "Indianapolis, IN"
        - "San Francisco, CA"
        - "Seattle, WA"
        - "Denver, CO"
        - "Oklahoma City, OK"
      log_prefix: "US"
    - country: "AE"
      domain: "ae.indeed.com"
      location_name: "United Arab Emirates"
      log_prefix: "AE"
    - country: "EG"
      domain: "indeed.com"
      location_name: "Egypt"
      log_prefix: "EG"
  
  parameters:
    - date_posted: "Last 14 days"
      posted_by: ""
      max_workers: 16
      poll_interval: 15
    - date_posted: "Last 7 days"
      posted_by: ""
      max_workers: 8
      poll_interval: 15
    - date_posted: "Last 24 hours"
      posted_by: ""
      max_workers: 16
      poll_interval: 15
    - date_posted: "Last 14 days"
      posted_by: ""
      max_workers: 8
      poll_interval: 15
    - date_posted: "Last 14 days"
      posted_by: ""
      max_workers: 8
      poll_interval: 15
        
# Environment overrides (optional, will use .env if not specified)
environment:
  # brightdata_api_key: "override_key_here"
  # aws_access_key: "override_key_here" 
  # aws_secret_key: "override_key_here"
  # s3_bucket: "override_bucket_here"
  # s3_directory: "override_directory_here"
  # dataset_id: "override_dataset_here"
