from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import psycopg2
from dotenv import load_dotenv
import os

load_dotenv("/home/ubuntu/airflow/.env")

# RDS PostgreSQL connection details
RDS_HOST = os.getenv("rds_endpoint")
DATABASE_NAME = os.getenv("db_name")
USERNAME = os.getenv("username")
PASSWORD = os.getenv("password")
PORT = "5432"  # Default PostgreSQL port

try:
    # Connect to PostgreSQL RDS
    conn = psycopg2.connect(
        dbname=DATABASE_NAME,
        user=USERNAME,
        password=PASSWORD,
        host=RDS_HOST,
        port=PORT
    )

    cursor = conn.cursor()

    # Create table using raw SQL
    create_raw_table_us_ca_query = f"""
    CREATE TABLE IF NOT EXISTS job_postings_us_ca (
        jobid TEXT,
        company_name TEXT,
        date_posted_parsed TIMESTAMP WITH TIME ZONE,
        job_title TEXT,
        description_text TEXT,
        benefits JSONB,
        qualifications TEXT,
        job_type TEXT,
        location TEXT,
        salary_formatted TEXT,
        company_rating NUMERIC(2,1),
        company_reviews_count INTEGER,
        country TEXT,
        date_posted TEXT,
        description TEXT,
        region TEXT,
        company_link TEXT,
        company_website TEXT,
        domain TEXT,
        apply_link TEXT,
        srcname TEXT,
        url TEXT,
        is_expired BOOLEAN,
        discovery_input JSONB,
        job_location TEXT,
        job_description_formatted TEXT,
        logo_url TEXT,
        timestamp TIMESTAMP WITH TIME ZONE,
        requested_timestamp TIMESTAMP WITH TIME ZONE,
        input JSONB,
        warning TEXT,
        error TEXT,
        error_code TEXT,
        screenshot TEXT,
        html TEXT,
        page_id TEXT,
        job_id TEXT,
        collector_id TEXT,
        collector_queue TEXT,
        reparse_file TEXT,
        warning_code TEXT
    );
    """

    cursor.execute(create_raw_table_us_ca_query)

    create_raw_table_query = f"""
    CREATE TABLE IF NOT EXISTS raw_new (
        name TEXT,
        key TEXT,
        title TEXT,
        location TEXT,
        jobtype TEXT,
        posted TEXT,
        days_ago INTEGER,
        rating DECIMAL(2,1),
        experience TEXT,
        salary TEXT,
        education TEXT,
        feed TEXT,
        link TEXT,
        tools TEXT,
        soft_skills TEXT,
        industry_skills TEXT,
        description TEXT,
        search_keyword TEXT,
        "date" DATE,
        "year" INTEGER,
        "month" INTEGER
    );
    """

    cursor.execute(create_raw_table_query)

    create_preprocessed_table_query = f"""
    CREATE TABLE IF NOT EXISTS preprocessed_new (
        name TEXT,
        key TEXT,
        title TEXT,
        location TEXT,
        jobtype TEXT,
        posted TEXT,
        days_ago INTEGER,
        rating DECIMAL(2,1),
        experience TEXT,
        salary TEXT,
        education TEXT,
        feed TEXT,
        link TEXT,
        tools TEXT,
        soft_skills TEXT,
        industry_skills TEXT,
        description TEXT,
        search_keyword TEXT,
        "date" DATE,
        "year" INTEGER,
        "month" INTEGER,
        experience_required INTEGER,
        bachelor INTEGER,
        master INTEGER,
        phd INTEGER,
        aws INTEGER,
        "microsoft access" INTEGER,
        azure INTEGER,
        c INTEGER,
        "c++" INTEGER,
        cassandra INTEGER,
        circleci INTEGER,
        cloud INTEGER,
        confluence INTEGER,
        databricks INTEGER,
        docker INTEGER,
        emr INTEGER,
        elasticsearch INTEGER,
        excel INTEGER,
        flask INTEGER,
        mlflow INTEGER,
        kubeflow INTEGER,
        gcp INTEGER,
        git INTEGER,
        github INTEGER,
        hadoop INTEGER,
        hive INTEGER,
        "hugging face" INTEGER,
        informatica INTEGER,
        jira INTEGER,
        java INTEGER,
        javascript INTEGER,
        jenkins INTEGER,
        kafka INTEGER,
        keras INTEGER,
        kubernetes INTEGER,
        llms INTEGER,
        matlab INTEGER,
        mongodb INTEGER,
        mysql INTEGER,
        "new relic" INTEGER,
        nosql INTEGER,
        numpy INTEGER,
        oracle INTEGER,
        outlook INTEGER,
        pandas INTEGER,
        postgresql INTEGER,
        postman INTEGER,
        "power bi" INTEGER,
        powerpoint INTEGER,
        pyspark INTEGER,
        python INTEGER,
        pytorch INTEGER,
        quicksight INTEGER,
        r INTEGER,
        redshift INTEGER,
        s3 INTEGER,
        sap INTEGER,
        sas INTEGER,
        soap INTEGER,
        spss INTEGER,
        sql INTEGER,
        "sql server" INTEGER,
        scala INTEGER,
        "scikit-learn" INTEGER,
        snowflake INTEGER,
        spacy INTEGER,
        spark INTEGER,
        streamlit INTEGER,
        tableau INTEGER,
        talend INTEGER,
        tensorflow INTEGER,
        terraform INTEGER,
        torch INTEGER,
        vba INTEGER,
        word INTEGER,
        xml INTEGER,
        transformer INTEGER,
        "ci/cd" INTEGER,
        accountability INTEGER,
        accuracy INTEGER,
        adaptability INTEGER,
        agility INTEGER,
        analysis INTEGER,
        "analytical skills" INTEGER,
        "attention to detail" INTEGER,
        coaching INTEGER,
        collaboration INTEGER,
        collaborative INTEGER,
        commitment INTEGER,
        communication INTEGER,
        "communication skills" INTEGER,
        confidence INTEGER,
        "continuous learning" INTEGER,
        coordination INTEGER,
        creativity INTEGER,
        "critical thinking" INTEGER,
        curiosity INTEGER,
        "decision making" INTEGER,
        "decision-making" INTEGER,
        dependability INTEGER,
        design INTEGER,
        discipline INTEGER,
        "domain knowledge" INTEGER,
        empathy INTEGER,
        enthusiasm INTEGER,
        experimentation INTEGER,
        flexibility INTEGER,
        focus INTEGER,
        friendliness INTEGER,
        imagination INTEGER,
        initiative INTEGER,
        innovation INTEGER,
        insight INTEGER,
        inspiring INTEGER,
        integrity INTEGER,
        "interpersonal skills" INTEGER,
        leadership INTEGER,
        mentorship INTEGER,
        motivated INTEGER,
        negotiation INTEGER,
        organization INTEGER,
        ownership INTEGER,
        passion INTEGER,
        persistence INTEGER,
        planning INTEGER,
        "presentation skills" INTEGER,
        prioritization INTEGER,
        prioritizing INTEGER,
        "problem-solving" INTEGER,
        professional INTEGER,
        "project management" INTEGER,
        reliable INTEGER,
        research INTEGER,
        resilient INTEGER,
        responsibility INTEGER,
        responsible INTEGER,
        "sense of urgency" INTEGER,
        storytelling INTEGER,
        "team player" INTEGER,
        teamwork INTEGER,
        "time management" INTEGER,
        "verbal communication" INTEGER,
        "work-life balance" INTEGER,
        "written communication" INTEGER,
        "written and oral communication" INTEGER,
        "api design" INTEGER,
        "api development" INTEGER,
        "batch processing" INTEGER,
        "big data" INTEGER,
        bioinformatics INTEGER,
        "business intelligence" INTEGER,
        classification INTEGER,
        "cloud computing" INTEGER,
        containerization INTEGER,
        "data analysis" INTEGER,
        "data architecture" INTEGER,
        "data cleaning" INTEGER,
        "data extraction" INTEGER,
        "data governance" INTEGER,
        "data ingestion" INTEGER,
        "data integration" INTEGER,
        "data manipulation" INTEGER,
        "data mining" INTEGER,
        "data modeling" INTEGER,
        "data pipelines" INTEGER,
        "data security" INTEGER,
        "data visualization" INTEGER,
        "data warehousing" INTEGER,
        "data wrangling" INTEGER,
        "database design" INTEGER,
        "deep learning" INTEGER,
        devops INTEGER,
        "distributed computing" INTEGER,
        etl INTEGER,
        econometrics INTEGER,
        extract INTEGER,
        "feature engineering" INTEGER,
        "google cloud" INTEGER,
        "load (etl) processes" INTEGER,
        logging INTEGER,
        ml INTEGER,
        "machine learning" INTEGER,
        mathematics INTEGER,
        metrics INTEGER,
        "microservices architecture" INTEGER,
        "model deployment" INTEGER,
        "model monitoring" INTEGER,
        monitoring INTEGER,
        nlp INTEGER,
        "natural language processing" INTEGER,
        "natural language understanding" INTEGER,
        "operations research" INTEGER,
        "problem-solving skills" INTEGER,
        "report generation" INTEGER,
        "research skills" INTEGER,
        scripting INTEGER,
        "statistical analysis" INTEGER,
        statistics INTEGER,
        "technical documentation" INTEGER,
        transform INTEGER,
        "understanding of machine learning algorithms" INTEGER
    );
    """
    cursor.execute(create_preprocessed_table_query)

    create_processed_table_query = f"""
    CREATE TABLE IF NOT EXISTS processed_new (
        name TEXT,
        key TEXT,
        title TEXT,
        location TEXT,
        jobtype TEXT,
        posted TEXT,
        days_ago INTEGER,
        rating DECIMAL(2,1),
        experience TEXT,
        salary TEXT,
        education TEXT,
        feed TEXT,
        link TEXT,
        tools TEXT,
        soft_skills TEXT,
        industry_skills TEXT,
        description TEXT,
        search_keyword TEXT,
        "date" DATE,
        "year" INTEGER,
        "month" INTEGER,
        experience_required INTEGER,
        bachelor INTEGER,
        master INTEGER,
        phd INTEGER,
        aws INTEGER,
        "microsoft access" INTEGER,
        azure INTEGER,
        c INTEGER,
        "c++" INTEGER,
        cassandra INTEGER,
        circleci INTEGER,
        cloud INTEGER,
        confluence INTEGER,
        databricks INTEGER,
        docker INTEGER,
        emr INTEGER,
        elasticsearch INTEGER,
        excel INTEGER,
        flask INTEGER,
        mlflow INTEGER,
        kubeflow INTEGER,
        gcp INTEGER,
        git INTEGER,
        github INTEGER,
        hadoop INTEGER,
        hive INTEGER,
        "hugging face" INTEGER,
        informatica INTEGER,
        jira INTEGER,
        java INTEGER,
        javascript INTEGER,
        jenkins INTEGER,
        kafka INTEGER,
        keras INTEGER,
        kubernetes INTEGER,
        llms INTEGER,
        matlab INTEGER,
        mongodb INTEGER,
        mysql INTEGER,
        "new relic" INTEGER,
        nosql INTEGER,
        numpy INTEGER,
        oracle INTEGER,
        outlook INTEGER,
        pandas INTEGER,
        postgresql INTEGER,
        postman INTEGER,
        "power bi" INTEGER,
        powerpoint INTEGER,
        pyspark INTEGER,
        python INTEGER,
        pytorch INTEGER,
        quicksight INTEGER,
        r INTEGER,
        redshift INTEGER,
        s3 INTEGER,
        sap INTEGER,
        sas INTEGER,
        soap INTEGER,
        spss INTEGER,
        sql INTEGER,
        "sql server" INTEGER,
        scala INTEGER,
        "scikit-learn" INTEGER,
        snowflake INTEGER,
        spacy INTEGER,
        spark INTEGER,
        streamlit INTEGER,
        tableau INTEGER,
        talend INTEGER,
        tensorflow INTEGER,
        terraform INTEGER,
        torch INTEGER,
        vba INTEGER,
        word INTEGER,
        xml INTEGER,
        transformer INTEGER,
        "ci/cd" INTEGER,
        accountability INTEGER,
        accuracy INTEGER,
        adaptability INTEGER,
        agility INTEGER,
        analysis INTEGER,
        "analytical skills" INTEGER,
        "attention to detail" INTEGER,
        coaching INTEGER,
        collaboration INTEGER,
        collaborative INTEGER,
        commitment INTEGER,
        communication INTEGER,
        "communication skills" INTEGER,
        confidence INTEGER,
        "continuous learning" INTEGER,
        coordination INTEGER,
        creativity INTEGER,
        "critical thinking" INTEGER,
        curiosity INTEGER,
        "decision making" INTEGER,
        "decision-making" INTEGER,
        dependability INTEGER,
        design INTEGER,
        discipline INTEGER,
        "domain knowledge" INTEGER,
        empathy INTEGER,
        enthusiasm INTEGER,
        experimentation INTEGER,
        flexibility INTEGER,
        focus INTEGER,
        friendliness INTEGER,
        imagination INTEGER,
        initiative INTEGER,
        innovation INTEGER,
        insight INTEGER,
        inspiring INTEGER,
        integrity INTEGER,
        "interpersonal skills" INTEGER,
        leadership INTEGER,
        mentorship INTEGER,
        motivated INTEGER,
        negotiation INTEGER,
        organization INTEGER,
        ownership INTEGER,
        passion INTEGER,
        persistence INTEGER,
        planning INTEGER,
        "presentation skills" INTEGER,
        prioritization INTEGER,
        prioritizing INTEGER,
        "problem-solving" INTEGER,
        professional INTEGER,
        "project management" INTEGER,
        reliable INTEGER,
        research INTEGER,
        resilient INTEGER,
        responsibility INTEGER,
        responsible INTEGER,
        "sense of urgency" INTEGER,
        storytelling INTEGER,
        "team player" INTEGER,
        teamwork INTEGER,
        "time management" INTEGER,
        "verbal communication" INTEGER,
        "work-life balance" INTEGER,
        "written communication" INTEGER,
        "written and oral communication" INTEGER,
        "api design" INTEGER,
        "api development" INTEGER,
        "batch processing" INTEGER,
        "big data" INTEGER,
        bioinformatics INTEGER,
        "business intelligence" INTEGER,
        classification INTEGER,
        "cloud computing" INTEGER,
        containerization INTEGER,
        "data analysis" INTEGER,
        "data architecture" INTEGER,
        "data cleaning" INTEGER,
        "data extraction" INTEGER,
        "data governance" INTEGER,
        "data ingestion" INTEGER,
        "data integration" INTEGER,
        "data manipulation" INTEGER,
        "data mining" INTEGER,
        "data modeling" INTEGER,
        "data pipelines" INTEGER,
        "data security" INTEGER,
        "data visualization" INTEGER,
        "data warehousing" INTEGER,
        "data wrangling" INTEGER,
        "database design" INTEGER,
        "deep learning" INTEGER,
        devops INTEGER,
        "distributed computing" INTEGER,
        etl INTEGER,
        econometrics INTEGER,
        extract INTEGER,
        "feature engineering" INTEGER,
        "google cloud" INTEGER,
        "load (etl) processes" INTEGER,
        logging INTEGER,
        ml INTEGER,
        "machine learning" INTEGER,
        mathematics INTEGER,
        metrics INTEGER,
        "microservices architecture" INTEGER,
        "model deployment" INTEGER,
        "model monitoring" INTEGER,
        monitoring INTEGER,
        nlp INTEGER,
        "natural language processing" INTEGER,
        "natural language understanding" INTEGER,
        "operations research" INTEGER,
        "problem-solving skills" INTEGER,
        "report generation" INTEGER,
        "research skills" INTEGER,
        scripting INTEGER,
        "statistical analysis" INTEGER,
        statistics INTEGER,
        "technical documentation" INTEGER,
        transform INTEGER,
        "understanding of machine learning algorithms" INTEGER,
        n_filter_words INTEGER
    );
    """
    cursor.execute(create_processed_table_query)

    create_LLM_labels_table_query = f"""
    CREATE TABLE IF NOT EXISTS LLM_labels_new (
        name TEXT,
        key TEXT,
        title TEXT,
        location TEXT,
        jobtype TEXT,
        posted TEXT,
        days_ago INTEGER,
        rating DECIMAL(2,1),
        experience TEXT,
        salary TEXT,
        education TEXT,
        feed TEXT,
        link TEXT,
        tools TEXT,
        soft_skills TEXT,
        industry_skills TEXT,
        description TEXT,
        search_keyword TEXT,
        label TEXT,
        "date" DATE,
        "year" INTEGER,
        "month" INTEGER,
        experience_required INTEGER,
        bachelor INTEGER,
        master INTEGER,
        phd INTEGER,
        aws INTEGER,
        "microsoft access" INTEGER,
        azure INTEGER,
        c INTEGER,
        "c++" INTEGER,
        cassandra INTEGER,
        circleci INTEGER,
        cloud INTEGER,
        confluence INTEGER,
        databricks INTEGER,
        docker INTEGER,
        emr INTEGER,
        elasticsearch INTEGER,
        excel INTEGER,
        flask INTEGER,
        mlflow INTEGER,
        kubeflow INTEGER,
        gcp INTEGER,
        git INTEGER,
        github INTEGER,
        hadoop INTEGER,
        hive INTEGER,
        "hugging face" INTEGER,
        informatica INTEGER,
        jira INTEGER,
        java INTEGER,
        javascript INTEGER,
        jenkins INTEGER,
        kafka INTEGER,
        keras INTEGER,
        kubernetes INTEGER,
        llms INTEGER,
        matlab INTEGER,
        mongodb INTEGER,
        mysql INTEGER,
        "new relic" INTEGER,
        nosql INTEGER,
        numpy INTEGER,
        oracle INTEGER,
        outlook INTEGER,
        pandas INTEGER,
        postgresql INTEGER,
        postman INTEGER,
        "power bi" INTEGER,
        powerpoint INTEGER,
        pyspark INTEGER,
        python INTEGER,
        pytorch INTEGER,
        quicksight INTEGER,
        r INTEGER,
        redshift INTEGER,
        s3 INTEGER,
        sap INTEGER,
        sas INTEGER,
        soap INTEGER,
        spss INTEGER,
        sql INTEGER,
        "sql server" INTEGER,
        scala INTEGER,
        "scikit-learn" INTEGER,
        snowflake INTEGER,
        spacy INTEGER,
        spark INTEGER,
        streamlit INTEGER,
        tableau INTEGER,
        talend INTEGER,
        tensorflow INTEGER,
        terraform INTEGER,
        torch INTEGER,
        vba INTEGER,
        word INTEGER,
        xml INTEGER,
        transformer INTEGER,
        "ci/cd" INTEGER,
        accountability INTEGER,
        accuracy INTEGER,
        adaptability INTEGER,
        agility INTEGER,
        analysis INTEGER,
        "analytical skills" INTEGER,
        "attention to detail" INTEGER,
        coaching INTEGER,
        collaboration INTEGER,
        collaborative INTEGER,
        commitment INTEGER,
        communication INTEGER,
        "communication skills" INTEGER,
        confidence INTEGER,
        "continuous learning" INTEGER,
        coordination INTEGER,
        creativity INTEGER,
        "critical thinking" INTEGER,
        curiosity INTEGER,
        "decision making" INTEGER,
        "decision-making" INTEGER,
        dependability INTEGER,
        design INTEGER,
        discipline INTEGER,
        "domain knowledge" INTEGER,
        empathy INTEGER,
        enthusiasm INTEGER,
        experimentation INTEGER,
        flexibility INTEGER,
        focus INTEGER,
        friendliness INTEGER,
        imagination INTEGER,
        initiative INTEGER,
        innovation INTEGER,
        insight INTEGER,
        inspiring INTEGER,
        integrity INTEGER,
        "interpersonal skills" INTEGER,
        leadership INTEGER,
        mentorship INTEGER,
        motivated INTEGER,
        negotiation INTEGER,
        organization INTEGER,
        ownership INTEGER,
        passion INTEGER,
        persistence INTEGER,
        planning INTEGER,
        "presentation skills" INTEGER,
        prioritization INTEGER,
        prioritizing INTEGER,
        "problem-solving" INTEGER,
        professional INTEGER,
        "project management" INTEGER,
        reliable INTEGER,
        research INTEGER,
        resilient INTEGER,
        responsibility INTEGER,
        responsible INTEGER,
        "sense of urgency" INTEGER,
        storytelling INTEGER,
        "team player" INTEGER,
        teamwork INTEGER,
        "time management" INTEGER,
        "verbal communication" INTEGER,
        "work-life balance" INTEGER,
        "written communication" INTEGER,
        "written and oral communication" INTEGER,
        "api design" INTEGER,
        "api development" INTEGER,
        "batch processing" INTEGER,
        "big data" INTEGER,
        bioinformatics INTEGER,
        "business intelligence" INTEGER,
        classification INTEGER,
        "cloud computing" INTEGER,
        containerization INTEGER,
        "data analysis" INTEGER,
        "data architecture" INTEGER,
        "data cleaning" INTEGER,
        "data extraction" INTEGER,
        "data governance" INTEGER,
        "data ingestion" INTEGER,
        "data integration" INTEGER,
        "data manipulation" INTEGER,
        "data mining" INTEGER,
        "data modeling" INTEGER,
        "data pipelines" INTEGER,
        "data security" INTEGER,
        "data visualization" INTEGER,
        "data warehousing" INTEGER,
        "data wrangling" INTEGER,
        "database design" INTEGER,
        "deep learning" INTEGER,
        devops INTEGER,
        "distributed computing" INTEGER,
        etl INTEGER,
        econometrics INTEGER,
        extract INTEGER,
        "feature engineering" INTEGER,
        "google cloud" INTEGER,
        "load (etl) processes" INTEGER,
        logging INTEGER,
        ml INTEGER,
        "machine learning" INTEGER,
        mathematics INTEGER,
        metrics INTEGER,
        "microservices architecture" INTEGER,
        "model deployment" INTEGER,
        "model monitoring" INTEGER,
        monitoring INTEGER,
        nlp INTEGER,
        "natural language processing" INTEGER,
        "natural language understanding" INTEGER,
        "operations research" INTEGER,
        "problem-solving skills" INTEGER,
        "report generation" INTEGER,
        "research skills" INTEGER,
        scripting INTEGER,
        "statistical analysis" INTEGER,
        statistics INTEGER,
        "technical documentation" INTEGER,
        transform INTEGER,
        "understanding of machine learning algorithms" INTEGER,
        n_filter_words INTEGER
    );
    """
    cursor.execute(create_LLM_labels_table_query)
    conn.commit()

except Exception as e:
    print(f"Error: {e}")

finally:
    # Close the database connection
    if conn:
        cursor.close()
        conn.close()
        print("PostgreSQL connection closed.")
