# List of all tables to upload csv data to
table_names = ['raw_new', 'preprocessed_new', 'processed_new', 'LLM_labels_new']

# CSV files to upload/update to S3 and RDS PostgreSQL
csv_file_paths = [
    "/home/ubuntu/airflow/outputs/concatenated_data.csv",
    "/home/ubuntu/airflow/outputs/preprocessed_data.csv",
    "/home/ubuntu/airflow/outputs/processed_data.csv",
    "/home/ubuntu/airflow/outputs/LLM_labels_data.csv",
]

# Copy data from csv files to temp tables
sql_copy_to_temp_queries = [
    "COPY raw_temp FROM STDIN WITH CSV HEADER",
    "COPY preprocessed_temp FROM STDIN WITH CSV HEADER",
    "COPY processed_temp FROM STDIN WITH CSV HEADER",
    "COPY LLM_labels_temp FROM STDIN WITH CSV HEADER"
]

# Create temp tables for the data load/merge
sql_temp_table_queries = [
    '''
    CREATE TEMPORARY TABLE IF NOT EXISTS raw_temp (
        name TEXT,
        key TEXT,
        title TEXT,
        location TEXT,
        jobtype TEXT,
        posted TEXT,
        days_ago INTEGER,
        rating DECIMAL(2,1),
        experience TEXT,
        salary TEXT,
        education TEXT,
        feed TEXT,
        link TEXT,
        tools TEXT,
        soft_skills TEXT,
        industry_skills TEXT,
        description TEXT,
        search_keyword TEXT,
        "date" DATE,
        "year" INTEGER,
        "month" INTEGER
    );
    ''',
    '''
    CREATE TEMPORARY TABLE IF NOT EXISTS preprocessed_temp (
        name TEXT,
        key TEXT,
        title TEXT,
        location TEXT,
        jobtype TEXT,
        posted TEXT,
        days_ago INTEGER,
        rating DECIMAL(2,1),
        experience TEXT,
        salary TEXT,
        education TEXT,
        feed TEXT,
        link TEXT,
        tools TEXT,
        soft_skills TEXT,
        industry_skills TEXT,
        description TEXT,
        search_keyword TEXT,
        "date" DATE,
        "year" INTEGER,
        "month" INTEGER,
        experience_required INTEGER,
        bachelor INTEGER,
        master INTEGER,
        phd INTEGER,
        aws INTEGER,
        "microsoft access" INTEGER,
        azure INTEGER,
        c INTEGER,
        "c++" INTEGER,
        cassandra INTEGER,
        circleci INTEGER,
        cloud INTEGER,
        confluence INTEGER,
        databricks INTEGER,
        docker INTEGER,
        emr INTEGER,
        elasticsearch INTEGER,
        excel INTEGER,
        flask INTEGER,
        mlflow INTEGER,
        kubeflow INTEGER,
        gcp INTEGER,
        git INTEGER,
        github INTEGER,
        hadoop INTEGER,
        hive INTEGER,
        "hugging face" INTEGER,
        informatica INTEGER,
        jira INTEGER,
        java INTEGER,
        javascript INTEGER,
        jenkins INTEGER,
        kafka INTEGER,
        keras INTEGER,
        kubernetes INTEGER,
        llms INTEGER,
        matlab INTEGER,
        mongodb INTEGER,
        mysql INTEGER,
        "new relic" INTEGER,
        nosql INTEGER,
        numpy INTEGER,
        oracle INTEGER,
        outlook INTEGER,
        pandas INTEGER,
        postgresql INTEGER,
        postman INTEGER,
        "power bi" INTEGER,
        powerpoint INTEGER,
        pyspark INTEGER,
        python INTEGER,
        pytorch INTEGER,
        quicksight INTEGER,
        r INTEGER,
        redshift INTEGER,
        s3 INTEGER,
        sap INTEGER,
        sas INTEGER,
        soap INTEGER,
        spss INTEGER,
        sql INTEGER,
        "sql server" INTEGER,
        scala INTEGER,
        "scikit-learn" INTEGER,
        snowflake INTEGER,
        spacy INTEGER,
        spark INTEGER,
        streamlit INTEGER,
        tableau INTEGER,
        talend INTEGER,
        tensorflow INTEGER,
        terraform INTEGER,
        torch INTEGER,
        vba INTEGER,
        word INTEGER,
        xml INTEGER,
        transformer INTEGER,
        "ci/cd" INTEGER,
        accountability INTEGER,
        accuracy INTEGER,
        adaptability INTEGER,
        agility INTEGER,
        analysis INTEGER,
        "analytical skills" INTEGER,
        "attention to detail" INTEGER,
        coaching INTEGER,
        collaboration INTEGER,
        collaborative INTEGER,
        commitment INTEGER,
        communication INTEGER,
        "communication skills" INTEGER,
        confidence INTEGER,
        "continuous learning" INTEGER,
        coordination INTEGER,
        creativity INTEGER,
        "critical thinking" INTEGER,
        curiosity INTEGER,
        "decision making" INTEGER,
        "decision-making" INTEGER,
        dependability INTEGER,
        design INTEGER,
        discipline INTEGER,
        "domain knowledge" INTEGER,
        empathy INTEGER,
        enthusiasm INTEGER,
        experimentation INTEGER,
        flexibility INTEGER,
        focus INTEGER,
        friendliness INTEGER,
        imagination INTEGER,
        initiative INTEGER,
        innovation INTEGER,
        insight INTEGER,
        inspiring INTEGER,
        integrity INTEGER,
        "interpersonal skills" INTEGER,
        leadership INTEGER,
        mentorship INTEGER,
        motivated INTEGER,
        negotiation INTEGER,
        organization INTEGER,
        ownership INTEGER,
        passion INTEGER,
        persistence INTEGER,
        planning INTEGER,
        "presentation skills" INTEGER,
        prioritization INTEGER,
        prioritizing INTEGER,
        "problem-solving" INTEGER,
        professional INTEGER,
        "project management" INTEGER,
        reliable INTEGER,
        research INTEGER,
        resilient INTEGER,
        responsibility INTEGER,
        responsible INTEGER,
        "sense of urgency" INTEGER,
        storytelling INTEGER,
        "team player" INTEGER,
        teamwork INTEGER,
        "time management" INTEGER,
        "verbal communication" INTEGER,
        "work-life balance" INTEGER,
        "written communication" INTEGER,
        "written and oral communication" INTEGER,
        "api design" INTEGER,
        "api development" INTEGER,
        "batch processing" INTEGER,
        "big data" INTEGER,
        bioinformatics INTEGER,
        "business intelligence" INTEGER,
        classification INTEGER,
        "cloud computing" INTEGER,
        containerization INTEGER,
        "data analysis" INTEGER,
        "data architecture" INTEGER,
        "data cleaning" INTEGER,
        "data extraction" INTEGER,
        "data governance" INTEGER,
        "data ingestion" INTEGER,
        "data integration" INTEGER,
        "data manipulation" INTEGER,
        "data mining" INTEGER,
        "data modeling" INTEGER,
        "data pipelines" INTEGER,
        "data security" INTEGER,
        "data visualization" INTEGER,
        "data warehousing" INTEGER,
        "data wrangling" INTEGER,
        "database design" INTEGER,
        "deep learning" INTEGER,
        devops INTEGER,
        "distributed computing" INTEGER,
        etl INTEGER,
        econometrics INTEGER,
        extract INTEGER,
        "feature engineering" INTEGER,
        "google cloud" INTEGER,
        "load (etl) processes" INTEGER,
        logging INTEGER,
        ml INTEGER,
        "machine learning" INTEGER,
        mathematics INTEGER,
        metrics INTEGER,
        "microservices architecture" INTEGER,
        "model deployment" INTEGER,
        "model monitoring" INTEGER,
        monitoring INTEGER,
        nlp INTEGER,
        "natural language processing" INTEGER,
        "natural language understanding" INTEGER,
        "operations research" INTEGER,
        "problem-solving skills" INTEGER,
        "report generation" INTEGER,
        "research skills" INTEGER,
        scripting INTEGER,
        "statistical analysis" INTEGER,
        statistics INTEGER,
        "technical documentation" INTEGER,
        transform INTEGER,
        "understanding of machine learning algorithms" INTEGER
    );
    ''',
    '''
    CREATE TEMPORARY TABLE IF NOT EXISTS processed_temp (
        name TEXT,
        key TEXT,
        title TEXT,
        location TEXT,
        jobtype TEXT,
        posted TEXT,
        days_ago INTEGER,
        rating DECIMAL(2,1),
        experience TEXT,
        salary TEXT,
        education TEXT,
        feed TEXT,
        link TEXT,
        tools TEXT,
        soft_skills TEXT,
        industry_skills TEXT,
        description TEXT,
        search_keyword TEXT,
        "date" DATE,
        "year" INTEGER,
        "month" INTEGER,
        experience_required INTEGER,
        bachelor INTEGER,
        master INTEGER,
        phd INTEGER,
        aws INTEGER,
        "microsoft access" INTEGER,
        azure INTEGER,
        c INTEGER,
        "c++" INTEGER,
        cassandra INTEGER,
        circleci INTEGER,
        cloud INTEGER,
        confluence INTEGER,
        databricks INTEGER,
        docker INTEGER,
        emr INTEGER,
        elasticsearch INTEGER,
        excel INTEGER,
        flask INTEGER,
        mlflow INTEGER,
        kubeflow INTEGER,
        gcp INTEGER,
        git INTEGER,
        github INTEGER,
        hadoop INTEGER,
        hive INTEGER,
        "hugging face" INTEGER,
        informatica INTEGER,
        jira INTEGER,
        java INTEGER,
        javascript INTEGER,
        jenkins INTEGER,
        kafka INTEGER,
        keras INTEGER,
        kubernetes INTEGER,
        llms INTEGER,
        matlab INTEGER,
        mongodb INTEGER,
        mysql INTEGER,
        "new relic" INTEGER,
        nosql INTEGER,
        numpy INTEGER,
        oracle INTEGER,
        outlook INTEGER,
        pandas INTEGER,
        postgresql INTEGER,
        postman INTEGER,
        "power bi" INTEGER,
        powerpoint INTEGER,
        pyspark INTEGER,
        python INTEGER,
        pytorch INTEGER,
        quicksight INTEGER,
        r INTEGER,
        redshift INTEGER,
        s3 INTEGER,
        sap INTEGER,
        sas INTEGER,
        soap INTEGER,
        spss INTEGER,
        sql INTEGER,
        "sql server" INTEGER,
        scala INTEGER,
        "scikit-learn" INTEGER,
        snowflake INTEGER,
        spacy INTEGER,
        spark INTEGER,
        streamlit INTEGER,
        tableau INTEGER,
        talend INTEGER,
        tensorflow INTEGER,
        terraform INTEGER,
        torch INTEGER,
        vba INTEGER,
        word INTEGER,
        xml INTEGER,
        transformer INTEGER,
        "ci/cd" INTEGER,
        accountability INTEGER,
        accuracy INTEGER,
        adaptability INTEGER,
        agility INTEGER,
        analysis INTEGER,
        "analytical skills" INTEGER,
        "attention to detail" INTEGER,
        coaching INTEGER,
        collaboration INTEGER,
        collaborative INTEGER,
        commitment INTEGER,
        communication INTEGER,
        "communication skills" INTEGER,
        confidence INTEGER,
        "continuous learning" INTEGER,
        coordination INTEGER,
        creativity INTEGER,
        "critical thinking" INTEGER,
        curiosity INTEGER,
        "decision making" INTEGER,
        "decision-making" INTEGER,
        dependability INTEGER,
        design INTEGER,
        discipline INTEGER,
        "domain knowledge" INTEGER,
        empathy INTEGER,
        enthusiasm INTEGER,
        experimentation INTEGER,
        flexibility INTEGER,
        focus INTEGER,
        friendliness INTEGER,
        imagination INTEGER,
        initiative INTEGER,
        innovation INTEGER,
        insight INTEGER,
        inspiring INTEGER,
        integrity INTEGER,
        "interpersonal skills" INTEGER,
        leadership INTEGER,
        mentorship INTEGER,
        motivated INTEGER,
        negotiation INTEGER,
        organization INTEGER,
        ownership INTEGER,
        passion INTEGER,
        persistence INTEGER,
        planning INTEGER,
        "presentation skills" INTEGER,
        prioritization INTEGER,
        prioritizing INTEGER,
        "problem-solving" INTEGER,
        professional INTEGER,
        "project management" INTEGER,
        reliable INTEGER,
        research INTEGER,
        resilient INTEGER,
        responsibility INTEGER,
        responsible INTEGER,
        "sense of urgency" INTEGER,
        storytelling INTEGER,
        "team player" INTEGER,
        teamwork INTEGER,
        "time management" INTEGER,
        "verbal communication" INTEGER,
        "work-life balance" INTEGER,
        "written communication" INTEGER,
        "written and oral communication" INTEGER,
        "api design" INTEGER,
        "api development" INTEGER,
        "batch processing" INTEGER,
        "big data" INTEGER,
        bioinformatics INTEGER,
        "business intelligence" INTEGER,
        classification INTEGER,
        "cloud computing" INTEGER,
        containerization INTEGER,
        "data analysis" INTEGER,
        "data architecture" INTEGER,
        "data cleaning" INTEGER,
        "data extraction" INTEGER,
        "data governance" INTEGER,
        "data ingestion" INTEGER,
        "data integration" INTEGER,
        "data manipulation" INTEGER,
        "data mining" INTEGER,
        "data modeling" INTEGER,
        "data pipelines" INTEGER,
        "data security" INTEGER,
        "data visualization" INTEGER,
        "data warehousing" INTEGER,
        "data wrangling" INTEGER,
        "database design" INTEGER,
        "deep learning" INTEGER,
        devops INTEGER,
        "distributed computing" INTEGER,
        etl INTEGER,
        econometrics INTEGER,
        extract INTEGER,
        "feature engineering" INTEGER,
        "google cloud" INTEGER,
        "load (etl) processes" INTEGER,
        logging INTEGER,
        ml INTEGER,
        "machine learning" INTEGER,
        mathematics INTEGER,
        metrics INTEGER,
        "microservices architecture" INTEGER,
        "model deployment" INTEGER,
        "model monitoring" INTEGER,
        monitoring INTEGER,
        nlp INTEGER,
        "natural language processing" INTEGER,
        "natural language understanding" INTEGER,
        "operations research" INTEGER,
        "problem-solving skills" INTEGER,
        "report generation" INTEGER,
        "research skills" INTEGER,
        scripting INTEGER,
        "statistical analysis" INTEGER,
        statistics INTEGER,
        "technical documentation" INTEGER,
        transform INTEGER,
        "understanding of machine learning algorithms" INTEGER,
        n_filter_words INTEGER
    );
    ''',
    '''
    CREATE TEMPORARY TABLE IF NOT EXISTS LLM_labels_temp (
        name TEXT,
        key TEXT,
        title TEXT,
        location TEXT,
        jobtype TEXT,
        posted TEXT,
        days_ago INTEGER,
        rating DECIMAL(2,1),
        experience TEXT,
        salary TEXT,
        education TEXT,
        feed TEXT,
        link TEXT,
        tools TEXT,
        soft_skills TEXT,
        industry_skills TEXT,
        description TEXT,
        search_keyword TEXT,
        label TEXT,
        "date" DATE,
        "year" INTEGER,
        "month" INTEGER,
        experience_required INTEGER,
        bachelor INTEGER,
        master INTEGER,
        phd INTEGER,
        aws INTEGER,
        "microsoft access" INTEGER,
        azure INTEGER,
        c INTEGER,
        "c++" INTEGER,
        cassandra INTEGER,
        circleci INTEGER,
        cloud INTEGER,
        confluence INTEGER,
        databricks INTEGER,
        docker INTEGER,
        emr INTEGER,
        elasticsearch INTEGER,
        excel INTEGER,
        flask INTEGER,
        mlflow INTEGER,
        kubeflow INTEGER,
        gcp INTEGER,
        git INTEGER,
        github INTEGER,
        hadoop INTEGER,
        hive INTEGER,
        "hugging face" INTEGER,
        informatica INTEGER,
        jira INTEGER,
        java INTEGER,
        javascript INTEGER,
        jenkins INTEGER,
        kafka INTEGER,
        keras INTEGER,
        kubernetes INTEGER,
        llms INTEGER,
        matlab INTEGER,
        mongodb INTEGER,
        mysql INTEGER,
        "new relic" INTEGER,
        nosql INTEGER,
        numpy INTEGER,
        oracle INTEGER,
        outlook INTEGER,
        pandas INTEGER,
        postgresql INTEGER,
        postman INTEGER,
        "power bi" INTEGER,
        powerpoint INTEGER,
        pyspark INTEGER,
        python INTEGER,
        pytorch INTEGER,
        quicksight INTEGER,
        r INTEGER,
        redshift INTEGER,
        s3 INTEGER,
        sap INTEGER,
        sas INTEGER,
        soap INTEGER,
        spss INTEGER,
        sql INTEGER,
        "sql server" INTEGER,
        scala INTEGER,
        "scikit-learn" INTEGER,
        snowflake INTEGER,
        spacy INTEGER,
        spark INTEGER,
        streamlit INTEGER,
        tableau INTEGER,
        talend INTEGER,
        tensorflow INTEGER,
        terraform INTEGER,
        torch INTEGER,
        vba INTEGER,
        word INTEGER,
        xml INTEGER,
        transformer INTEGER,
        "ci/cd" INTEGER,
        accountability INTEGER,
        accuracy INTEGER,
        adaptability INTEGER,
        agility INTEGER,
        analysis INTEGER,
        "analytical skills" INTEGER,
        "attention to detail" INTEGER,
        coaching INTEGER,
        collaboration INTEGER,
        collaborative INTEGER,
        commitment INTEGER,
        communication INTEGER,
        "communication skills" INTEGER,
        confidence INTEGER,
        "continuous learning" INTEGER,
        coordination INTEGER,
        creativity INTEGER,
        "critical thinking" INTEGER,
        curiosity INTEGER,
        "decision making" INTEGER,
        "decision-making" INTEGER,
        dependability INTEGER,
        design INTEGER,
        discipline INTEGER,
        "domain knowledge" INTEGER,
        empathy INTEGER,
        enthusiasm INTEGER,
        experimentation INTEGER,
        flexibility INTEGER,
        focus INTEGER,
        friendliness INTEGER,
        imagination INTEGER,
        initiative INTEGER,
        innovation INTEGER,
        insight INTEGER,
        inspiring INTEGER,
        integrity INTEGER,
        "interpersonal skills" INTEGER,
        leadership INTEGER,
        mentorship INTEGER,
        motivated INTEGER,
        negotiation INTEGER,
        organization INTEGER,
        ownership INTEGER,
        passion INTEGER,
        persistence INTEGER,
        planning INTEGER,
        "presentation skills" INTEGER,
        prioritization INTEGER,
        prioritizing INTEGER,
        "problem-solving" INTEGER,
        professional INTEGER,
        "project management" INTEGER,
        reliable INTEGER,
        research INTEGER,
        resilient INTEGER,
        responsibility INTEGER,
        responsible INTEGER,
        "sense of urgency" INTEGER,
        storytelling INTEGER,
        "team player" INTEGER,
        teamwork INTEGER,
        "time management" INTEGER,
        "verbal communication" INTEGER,
        "work-life balance" INTEGER,
        "written communication" INTEGER,
        "written and oral communication" INTEGER,
        "api design" INTEGER,
        "api development" INTEGER,
        "batch processing" INTEGER,
        "big data" INTEGER,
        bioinformatics INTEGER,
        "business intelligence" INTEGER,
        classification INTEGER,
        "cloud computing" INTEGER,
        containerization INTEGER,
        "data analysis" INTEGER,
        "data architecture" INTEGER,
        "data cleaning" INTEGER,
        "data extraction" INTEGER,
        "data governance" INTEGER,
        "data ingestion" INTEGER,
        "data integration" INTEGER,
        "data manipulation" INTEGER,
        "data mining" INTEGER,
        "data modeling" INTEGER,
        "data pipelines" INTEGER,
        "data security" INTEGER,
        "data visualization" INTEGER,
        "data warehousing" INTEGER,
        "data wrangling" INTEGER,
        "database design" INTEGER,
        "deep learning" INTEGER,
        devops INTEGER,
        "distributed computing" INTEGER,
        etl INTEGER,
        econometrics INTEGER,
        extract INTEGER,
        "feature engineering" INTEGER,
        "google cloud" INTEGER,
        "load (etl) processes" INTEGER,
        logging INTEGER,
        ml INTEGER,
        "machine learning" INTEGER,
        mathematics INTEGER,
        metrics INTEGER,
        "microservices architecture" INTEGER,
        "model deployment" INTEGER,
        "model monitoring" INTEGER,
        monitoring INTEGER,
        nlp INTEGER,
        "natural language processing" INTEGER,
        "natural language understanding" INTEGER,
        "operations research" INTEGER,
        "problem-solving skills" INTEGER,
        "report generation" INTEGER,
        "research skills" INTEGER,
        scripting INTEGER,
        "statistical analysis" INTEGER,
        statistics INTEGER,
        "technical documentation" INTEGER,
        transform INTEGER,
        "understanding of machine learning algorithms" INTEGER,
        n_filter_words INTEGER
    );
    ''',
]

# Merge data from temp tables (csv file data) into PostgreSQL tables. Only new data (from Airflow tasks) will get uploaded into PostgreSQL to ensure idempotency.
sql_merge_sql_queries = [
    '''
    INSERT INTO raw_new
    SELECT rt.name, rt.key, rt.title, rt.location, rt.jobtype, rt.posted, rt.days_ago, rt.rating, rt.experience, rt.salary, rt.education, rt.feed, rt.link, rt.tools, rt.soft_skills, rt.industry_skills, rt.description, rt.search_keyword, rt.date, rt.year, rt.month
    FROM raw_temp rt
    LEFT JOIN raw_new r ON rt.key = r.key
    AND rt.date = r.date
    AND rt.search_keyword = r.search_keyword
    WHERE r.key IS NULL;
    ''',
    '''
    INSERT INTO preprocessed_new
    SELECT 
        pt.name, pt.key, pt.title, pt.location, pt.jobtype, pt.posted, pt.days_ago, 
        pt.rating, pt.experience, pt.salary, pt.education, pt.feed, pt.link, 
        pt.tools, pt.soft_skills, pt.industry_skills, pt.description, 
        pt.search_keyword, pt."date", pt."year", pt."month", 
        pt.experience_required, pt.bachelor, pt.master, pt.phd, 
        pt.aws, pt."microsoft access", pt.azure, pt.c, pt."c++", pt.cassandra, 
        pt.circleci, pt.cloud, pt.confluence, pt.databricks, pt.docker, pt.emr, 
        pt.elasticsearch, pt.excel, pt.flask, pt.mlflow, pt.kubeflow, pt.gcp, 
        pt.git, pt.github, pt.hadoop, pt.hive, pt."hugging face", pt.informatica, 
        pt.jira, pt.java, pt.javascript, pt.jenkins, pt.kafka, pt.keras, 
        pt.kubernetes, pt.llms, pt.matlab, pt.mongodb, pt.mysql, pt."new relic", 
        pt.nosql, pt.numpy, pt.oracle, pt.outlook, pt.pandas, pt.postgresql, 
        pt.postman, pt."power bi", pt.powerpoint, pt.pyspark, pt.python, 
        pt.pytorch, pt.quicksight, pt.r, pt.redshift, pt.s3, pt.sap, pt.sas, 
        pt.soap, pt.spss, pt.sql, pt."sql server", pt.scala, pt."scikit-learn", 
        pt.snowflake, pt.spacy, pt.spark, pt.streamlit, pt.tableau, pt.talend, 
        pt.tensorflow, pt.terraform, pt.torch, pt.vba, pt.word, pt.xml, 
        pt.transformer, pt."ci/cd", pt.accountability, pt.accuracy, pt.adaptability, 
        pt.agility, pt.analysis, pt."analytical skills", pt."attention to detail", 
        pt.coaching, pt.collaboration, pt.collaborative, pt.commitment, 
        pt.communication, pt."communication skills", pt.confidence, 
        pt."continuous learning", pt.coordination, pt.creativity, 
        pt."critical thinking", pt.curiosity, pt."decision making", 
        pt."decision-making", pt.dependability, pt.design, pt.discipline, 
        pt."domain knowledge", pt.empathy, pt.enthusiasm, pt.experimentation, 
        pt.flexibility, pt.focus, pt.friendliness, pt.imagination, pt.initiative, 
        pt.innovation, pt.insight, pt.inspiring, pt.integrity, 
        pt."interpersonal skills", pt.leadership, pt.mentorship, pt.motivated, 
        pt.negotiation, pt.organization, pt.ownership, pt.passion, pt.persistence, 
        pt.planning, pt."presentation skills", pt.prioritization, pt.prioritizing, 
        pt."problem-solving", pt.professional, pt."project management", 
        pt.reliable, pt.research, pt.resilient, pt.responsibility, pt.responsible, 
        pt."sense of urgency", pt.storytelling, pt."team player", pt.teamwork, 
        pt."time management", pt."verbal communication", pt."work-life balance", 
        pt."written communication", pt."written and oral communication", 
        pt."api design", pt."api development", pt."batch processing", pt."big data", 
        pt.bioinformatics, pt."business intelligence", pt.classification, 
        pt."cloud computing", pt.containerization, pt."data analysis", 
        pt."data architecture", pt."data cleaning", pt."data extraction", 
        pt."data governance", pt."data ingestion", pt."data integration", 
        pt."data manipulation", pt."data mining", pt."data modeling", 
        pt."data pipelines", pt."data security", pt."data visualization", 
        pt."data warehousing", pt."data wrangling", pt."database design", 
        pt."deep learning", pt.devops, pt."distributed computing", pt.etl, 
        pt.econometrics, pt.extract, pt."feature engineering", pt."google cloud", 
        pt."load (etl) processes", pt.logging, pt.ml, pt."machine learning", 
        pt.mathematics, pt.metrics, pt."microservices architecture", 
        pt."model deployment", pt."model monitoring", pt.monitoring, pt.nlp, 
        pt."natural language processing", pt."natural language understanding", 
        pt."operations research", pt."problem-solving skills", pt."report generation", 
        pt."research skills", pt.scripting, pt."statistical analysis", pt.statistics, 
        pt."technical documentation", pt.transform, pt."understanding of machine learning algorithms"
    FROM preprocessed_temp pt
    LEFT JOIN preprocessed_new p on pt.key=p.key
    AND pt.date = p.date
    AND pt.search_keyword = p.search_keyword
    WHERE p.key IS NULL;
    ''',
    '''
    INSERT INTO processed_new
    SELECT 
        lft.name, lft.key, lft.title, lft.location, lft.jobtype, lft.posted, lft.days_ago, 
        lft.rating, lft.experience, lft.salary, lft.education, lft.feed, lft.link, 
        lft.tools, lft.soft_skills, lft.industry_skills, lft.description, 
        lft.search_keyword, lft."date", lft."year", lft."month", 
        lft.experience_required, lft.bachelor, lft.master, lft.phd, 
        lft.aws, lft."microsoft access", lft.azure, lft.c, lft."c++", lft.cassandra, 
        lft.circleci, lft.cloud, lft.confluence, lft.databricks, lft.docker, lft.emr, 
        lft.elasticsearch, lft.excel, lft.flask, lft.mlflow, lft.kubeflow, lft.gcp, 
        lft.git, lft.github, lft.hadoop, lft.hive, lft."hugging face", lft.informatica, 
        lft.jira, lft.java, lft.javascript, lft.jenkins, lft.kafka, lft.keras, 
        lft.kubernetes, lft.llms, lft.matlab, lft.mongodb, lft.mysql, lft."new relic", 
        lft.nosql, lft.numpy, lft.oracle, lft.outlook, lft.pandas, lft.postgresql, 
        lft.postman, lft."power bi", lft.powerpoint, lft.pyspark, lft.python, 
        lft.pytorch, lft.quicksight, lft.r, lft.redshift, lft.s3, lft.sap, lft.sas, 
        lft.soap, lft.spss, lft.sql, lft."sql server", lft.scala, lft."scikit-learn", 
        lft.snowflake, lft.spacy, lft.spark, lft.streamlit, lft.tableau, lft.talend, 
        lft.tensorflow, lft.terraform, lft.torch, lft.vba, lft.word, lft.xml, 
        lft.transformer, lft."ci/cd", lft.accountability, lft.accuracy, lft.adaptability, 
        lft.agility, lft.analysis, lft."analytical skills", lft."attention to detail", 
        lft.coaching, lft.collaboration, lft.collaborative, lft.commitment, 
        lft.communication, lft."communication skills", lft.confidence, 
        lft."continuous learning", lft.coordination, lft.creativity, 
        lft."critical thinking", lft.curiosity, lft."decision making", 
        lft."decision-making", lft.dependability, lft.design, lft.discipline, 
        lft."domain knowledge", lft.empathy, lft.enthusiasm, lft.experimentation, 
        lft.flexibility, lft.focus, lft.friendliness, lft.imagination, lft.initiative, 
        lft.innovation, lft.insight, lft.inspiring, lft.integrity, 
        lft."interpersonal skills", lft.leadership, lft.mentorship, lft.motivated, 
        lft.negotiation, lft.organization, lft.ownership, lft.passion, lft.persistence, 
        lft.planning, lft."presentation skills", lft.prioritization, lft.prioritizing, 
        lft."problem-solving", lft.professional, lft."project management", 
        lft.reliable, lft.research, lft.resilient, lft.responsibility, lft.responsible, 
        lft."sense of urgency", lft.storytelling, lft."team player", lft.teamwork, 
        lft."time management", lft."verbal communication", lft."work-life balance", 
        lft."written communication", lft."written and oral communication", 
        lft."api design", lft."api development", lft."batch processing", lft."big data", 
        lft.bioinformatics, lft."business intelligence", lft.classification, 
        lft."cloud computing", lft.containerization, lft."data analysis", 
        lft."data architecture", lft."data cleaning", lft."data extraction", 
        lft."data governance", lft."data ingestion", lft."data integration", 
        lft."data manipulation", lft."data mining", lft."data modeling", 
        lft."data pipelines", lft."data security", lft."data visualization", 
        lft."data warehousing", lft."data wrangling", lft."database design", 
        lft."deep learning", lft.devops, lft."distributed computing", lft.etl, 
        lft.econometrics, lft.extract, lft."feature engineering", lft."google cloud", 
        lft."load (etl) processes", lft.logging, lft.ml, lft."machine learning", 
        lft.mathematics, lft.metrics, lft."microservices architecture", 
        lft."model deployment", lft."model monitoring", lft.monitoring, lft.nlp, 
        lft."natural language processing", lft."natural language understanding", 
        lft."operations research", lft."problem-solving skills", lft."report generation", 
        lft."research skills", lft.scripting, lft."statistical analysis", lft.statistics, 
        lft."technical documentation", lft.transform, lft."understanding of machine learning algorithms",
        lft.n_filter_words
    FROM processed_temp lft
    LEFT JOIN processed_new lf on lft.key=lf.key
    AND lft.date = lf.date
    AND lft.search_keyword = lf.search_keyword
    WHERE lf.key IS NULL;
    ''',
    '''
    INSERT INTO LLM_labels_new
    SELECT 
        hft.name, hft.key, hft.title, hft.location, hft.jobtype, hft.posted, hft.days_ago, 
        hft.rating, hft.experience, hft.salary, hft.education, hft.feed, hft.link, 
        hft.tools, hft.soft_skills, hft.industry_skills, hft.description, 
        hft.search_keyword, hft.label, hft."date", hft."year", hft."month", 
        hft.experience_required, hft.bachelor, hft.master, hft.phd, 
        hft.aws, hft."microsoft access", hft.azure, hft.c, hft."c++", hft.cassandra, 
        hft.circleci, hft.cloud, hft.confluence, hft.databricks, hft.docker, hft.emr, 
        hft.elasticsearch, hft.excel, hft.flask, hft.mlflow, hft.kubeflow, hft.gcp, 
        hft.git, hft.github, hft.hadoop, hft.hive, hft."hugging face", hft.informatica, 
        hft.jira, hft.java, hft.javascript, hft.jenkins, hft.kafka, hft.keras, 
        hft.kubernetes, hft.llms, hft.matlab, hft.mongodb, hft.mysql, hft."new relic", 
        hft.nosql, hft.numpy, hft.oracle, hft.outlook, hft.pandas, hft.postgresql, 
        hft.postman, hft."power bi", hft.powerpoint, hft.pyspark, hft.python, 
        hft.pytorch, hft.quicksight, hft.r, hft.redshift, hft.s3, hft.sap, hft.sas, 
        hft.soap, hft.spss, hft.sql, hft."sql server", hft.scala, hft."scikit-learn", 
        hft.snowflake, hft.spacy, hft.spark, hft.streamlit, hft.tableau, hft.talend, 
        hft.tensorflow, hft.terraform, hft.torch, hft.vba, hft.word, hft.xml, 
        hft.transformer, hft."ci/cd", hft.accountability, hft.accuracy, hft.adaptability, 
        hft.agility, hft.analysis, hft."analytical skills", hft."attention to detail", 
        hft.coaching, hft.collaboration, hft.collaborative, hft.commitment, 
        hft.communication, hft."communication skills", hft.confidence, 
        hft."continuous learning", hft.coordination, hft.creativity, 
        hft."critical thinking", hft.curiosity, hft."decision making", 
        hft."decision-making", hft.dependability, hft.design, hft.discipline, 
        hft."domain knowledge", hft.empathy, hft.enthusiasm, hft.experimentation, 
        hft.flexibility, hft.focus, hft.friendliness, hft.imagination, hft.initiative, 
        hft.innovation, hft.insight, hft.inspiring, hft.integrity, 
        hft."interpersonal skills", hft.leadership, hft.mentorship, hft.motivated, 
        hft.negotiation, hft.organization, hft.ownership, hft.passion, hft.persistence, 
        hft.planning, hft."presentation skills", hft.prioritization, hft.prioritizing, 
        hft."problem-solving", hft.professional, hft."project management", 
        hft.reliable, hft.research, hft.resilient, hft.responsibility, hft.responsible, 
        hft."sense of urgency", hft.storytelling, hft."team player", hft.teamwork, 
        hft."time management", hft."verbal communication", hft."work-life balance", 
        hft."written communication", hft."written and oral communication", 
        hft."api design", hft."api development", hft."batch processing", hft."big data", 
        hft.bioinformatics, hft."business intelligence", hft.classification, 
        hft."cloud computing", hft.containerization, hft."data analysis", 
        hft."data architecture", hft."data cleaning", hft."data extraction", 
        hft."data governance", hft."data ingestion", hft."data integration", 
        hft."data manipulation", hft."data mining", hft."data modeling", 
        hft."data pipelines", hft."data security", hft."data visualization", 
        hft."data warehousing", hft."data wrangling", hft."database design", 
        hft."deep learning", hft.devops, hft."distributed computing", hft.etl, 
        hft.econometrics, hft.extract, hft."feature engineering", hft."google cloud", 
        hft."load (etl) processes", hft.logging, hft.ml, hft."machine learning", 
        hft.mathematics, hft.metrics, hft."microservices architecture", 
        hft."model deployment", hft."model monitoring", hft.monitoring, hft.nlp, 
        hft."natural language processing", hft."natural language understanding", 
        hft."operations research", hft."problem-solving skills", hft."report generation", 
        hft."research skills", hft.scripting, hft."statistical analysis", hft.statistics, 
        hft."technical documentation", hft.transform, hft."understanding of machine learning algorithms",
        hft.n_filter_words
    FROM LLM_labels_temp hft
    LEFT JOIN LLM_labels_new hf on hft.key=hf.key
    WHERE hf.key IS NULL;
    ''',
]

# Remove temp tables
sql_drop_temp_table_queries = [
    "DROP TABLE IF EXISTS raw_temp;",
    "DROP TABLE IF EXISTS preprocessed_temp;",
    "DROP TABLE IF EXISTS processed_temp;",
    "DROP TABLE IF EXISTS LLM_labels_temp;"
]
